### ISSUE TITLE
Ability to Flag a Project

### ISSUE THREAD

**Issue by cycomachead** [snap-cloud/snapCloud#135]
This is the most basic version, not full moderation but a scaffold so we don't shoot ourselves in the foot if we have any issues. And enough for us to successfully manually moderate if we run into issues, hopefully it's enough. 

See #110 

- a new `flags` table
- For now it should have the following schema:
    - project_id (foreign key on projects)
    - creator_id (FK on users)
    - created_at (timestamp w/tz)
    - updated_at  (timestamp w/tz)
    - project_updated_at  (timestamp w/tz)
    - reviewed boolean, default false
- a new endpoint POST /projects/:username/:projectname/flag
   - add a new flag for that project. Copy project updated_at to the flag

This is enough for us to build dashboards to review, and is simple enough to implement.

**Comment by bromagosa** [comment]
Done :+1:

All users can flag a project from the project page, but only admins, mods and reviewers can access the `Flagged projects` page via the `Administration` page. It's actually just a collection with `id == 0` owned by user `snapcloud`.

I guess we should add that to the migrations file so it gets created automatically on deploy?

**Comment by cycomachead** [comment]
Yeah, I think so. 👍 we should probably create the snapcloud user too. 

(Well there is technically some argument that you separate “seed” data and migrations, but since lapis doesn’t have a specific seed function, it’s good to keep it in migrations.)

**Comment by cycomachead** [comment]
So now that the site is released - and thinking about how we might want to support moderation in the future, I wonder if it makes sense to revisit the collections design? 

We can kinda make collections work, but I wonder if it makes sense to start building out this table/api that will be easier to adapt than collections? (which will probably stay simple, I hope.)

**Comment by bromagosa** [comment]
Yeah, I agree that a separate table would be best. A user that accidentally flags a project needs to be able to unflag it, and we also need to be able to count the times a project has been flagged so we can preventively auto-unpublish projects that receive lots of flags. The current design doesn't allow for either.

I hope to be able to spare some time for these things. I wish we'd have released three months ago when I did have the time :(

**Comment by bromagosa** [comment]
I'm closing this one now that we have a new flagging system. Let's open new issues if we find it misses any features.
