### ISSUE TITLE
Remix on save/save-as support

### ISSUE THREAD

**Issue by cycomachead** [snap-cloud/snapCloud#182]
I think saving a project opened from another user should trigger a remix even if you don't click that button. 

- we should always send down the projectId as at the remixID
Then for a save-as action when a new project it created a remix should be created.

**Comment by bromagosa** [comment]
Well, that's exactly how it works! :)

**Comment by bromagosa** [comment]
(this is handled at the frontend side, btw)

**Comment by cycomachead** [comment]
But a lot of projects don’t seem to have a remix ID? I opened one of my projects and was saving it as a new one and there’s no remix ID there. 

This was when I was testing the cloud.js changes last night.

**Comment by bromagosa** [comment]
Yep, because if the project is yours it's not considered a remix.

**Comment by cycomachead** [comment]
Hmm, I don't see why not. If you're gonna make a few different version of something, I think you should be able to remix yourself.

**Comment by bromagosa** [comment]
Is Scratch handling it like this? @jmoenig, @brianharvey, any thoughts?

**Comment by brianharvey** [comment]
Afaik, Scratch doesn't let you remix yourself.  Typically, a remix has (at least at first) the same project name as the original, so it's not clear how you'd have two projects with the same name.

I think the whole reason for a remix feature is to encourage users to enhance each others' projects, and to ensure that the original author is credited.  Michael, what's the point of remixing yourself?

**Comment by jmoenig** [comment]
I agree with Brian and Bernat. I guess it might be interesting to track your own project's genealogy, but I wouldn't call it a "remix" unless it's from someone else.

**Comment by cycomachead** [comment]
If you can’t rename a project then sure you can’t have two of the same thing (which is why forking on GitHub doesn’t work.)

I guess to me I’ve always thought of a remix as a variation on some idea. Why does it matter if your friend had the idea or you did if the end result is similar? We intend to store remixes that go you->friend->you. So I don’t really see why an intermediary is so different in the history of a project. 

And I do really think seeing your own history is useful and maybe interesting. Or at least, I think it is for the people who save lots of versions of a project. If you have a bunch of similar versions then having them linked together helps you  (Or others!) find what you need. 

I guess I also don’t see the harm in storing that data? If people really found it annoying you’d just filter out projects from the same author. 

But otherwise, if I am making 2 versions of the same game, I _do_ want them to be linked together in some way. 
-- 
Michael Ball
From my iPhone
michaelball.co

**Comment by brianharvey** [comment]
I suppose we could keep the history information, but only _call it_ a "remix" if it's someone else's project.

**Comment by cycomachead** [comment]
I still don’t see why? 

I suppose if we are thinking of a counter, that makes more sense. 
But if we are just listing them on a page... I don’t know that it makes a huge difference. 

But if we store the links we can very easily separate them. 
-- 
Michael Ball
From my iPhone
michaelball.co
