### ISSUE TITLE
Return all columns of an object in all responses

### ISSUE THREAD

**Issue by cycomachead** [snap-cloud/snapCloud#197]
Huh... so values which are NULL in the database don't get returned by default when you serialize an object as JSON. 

This seems pretty unconventional for an API, though there's not a good work around right now. :(

**Comment by bromagosa** [comment]
Hmm. Can you show an example where this happens?

**Comment by cycomachead** [comment]
I noticed it when querying for an individual collection. 

https://cloud.snap.berkeley.edu/site/project.html?user=cycomachead&project=New%20Test%20Project%3Cp%3ETest%3C%2Fp%3E%C2%A0

Look at the metadata response for a private project. (Any private project should work.)
This isn't shared, so there's no shared or published date fields. I'd expect the API to return null for such fields -- declaring that they're part of the response.

In practice, we can kind of avoid this issue -- it's mostly an oddity. But it is a minor annoyance for clients since you might need to worry about null vs undefined in JS. (Or if you were using a typed environment, this could be annoying to work around.)

**Comment by bromagosa** [comment]
I see. Yeah, this is definitely super low priority :)

**Comment by cycomachead** [comment]
It's not even a low priority... it's excruciatingly difficult to work around, lol.
