### ISSUE TITLE
Snap! Cloud Server certificate issue

### ISSUE THREAD

**Issue by mikep345678** [snap-cloud/snapCloud#231]
[for redundancy, pasted from submission to Snap! forum...]

1. What browsers show this problem?
Chrome 77.0.3865.120

2. Please share an example project (if possible).
any/all

3. Describes the steps to reproduce this issue. 
a. Launch Snap! via http://amazingrobots.net/snap/snap.html or http://snap4arduino.rocks/run/#
b. open Chrome Developers Tools
c. notice console error message: Failed to load resource: cloud.snap.berkeley.edu/api/v1/init:1 Failed to load net::ERR_CERT_DATE_INVALID
d. Attempt to sign in to Snap! (cloud)
e. Feel rejected by Snap
f. notice console error message: cloud.js?version=2019-07-17:217 OPTIONS https://cloud.snap.berkeley.edu/api/v1/users/mikep345678/login?persist=true net::ERR_CERT_DATE_INVALID
![image](https://user-images.githubusercontent.com/886724/66938996-d75acc00-f007-11e9-82ba-f2f021016637.png)

4. What does Snap<em>!</em> currently do?
Not communicate with Snap! cloud server!

5. What should Snap<em>!</em> do instead?
Communicate with Snap! cloud server!

**Comment by mikep345678** [comment]
As of this afternoon, the issue appears to have resolved itself.

Do we know why this happened?

**Comment by cycomachead** [comment]
Yeah, the cert expired and the automation failed for putting the cert in the right spot.

The cloud.snap.berkeley domain wasn't intended to be used anymore, but some tools need to update their domains. The better URL is snap.berkeley.edu. We didn't communicate this to extensions authors because things happened kind of quickly, so we do intend to keep it alive. (It's merely an alias at this point.)

**Comment by mikep345678** [comment]
Ah, OK! Thanks for explaining. I see that the cloud URL was just updated in the Snap! source a few days ago...


Thank you!
Mike

**Comment by cycomachead** [comment]
Yeah, we have a little thing in the nginx side that sets the cloud API URL dynamically which has been working and it worked so well we forgot to update cloud.js sooner. 

-- 
Michael Ball
From my iPhone
michaelball.co
