### ISSUE TITLE
Users Can Remove Their Own Projects From Free For All Collections

### ISSUE THREAD

**Issue by cycomachead** [snap-cloud/snapCloud#267]
...except the flagged one, which remains special. ;)

**Comment by bromagosa** [comment]
That's a spec description, right?

Cos if it's a description of what's happening right now, I don't know how that happened! :laughing:

**Comment by cycomachead** [comment]
Oh yeah, it's a written as a spec. Been in that mode teaching students things. 😁

**Comment by cycomachead** [comment]
Hmm. I thought we would have addressed this with the recent fix, but a non-admin user still can't remove their own projects...
