### ISSUE TITLE
cloud.sql + migration file column conflict

### ISSUE THREAD

**Issue by ochan1** [snap-cloud/snapCloud#281]
When running the bin/migrations.sh script to apply the database migrations to my Postgresql local database, there are two columns in conflict in particular: 
* projects.deleted
* users.deleted

Since the cloud.sql already has these columns inside, the migration would fail, stating that it can't add a column that the table already has and it errors out

As a result, two of the following needs to happen:
1. Remove the "projects.deleted" and "users.deleted" column from the cloud.sql, so the migration can add them in for you
2. Remove the "2019-02-01:0" migration in the migrations.lua file, but that may affect the original server if this migration file is used

Number 1 would be safer since the cloud.sql looks to be just a starting point, while migration files need more discussion if removing the specific migration would do any hard when deploying

Mainly, if cloud.sql is the SQL to help us initialize our database, then it's better to remove directly from the cloud.sql rather than migrations.lua

**Comment by ochan1** [comment]
Small commenting-out change branch with change Number 2 done here: https://github.com/ochan1/snapCloud/tree/modified_migration_for_cloud_sql

**Comment by cycomachead** [comment]
Thanks for reporting this. #291 should hopefully address this for good.
