### ISSUE TITLE
Applying migrations.sh as per INSTALL.md dies

### ISSUE THREAD

**Issue by opencoca** [snap-cloud/snapCloud#321]
When installing on ubuntu 20.04, the current bin/migrations.sh fails to add deleted to users.

```
/usr/local/share/lua/5.1/lapis/db/postgres.lua:111: ALTER TABLE "users" ADD COLUMN "deleted" timestamp with time zone
 ERROR: column "deleted" of relation "users" already exists
```

**Comment by opencoca** [comment]
A hack that gets things working is to patch the migrations. Not including the broken instructions may have side effects, as I'm unfamiliar with all aspects of the DB and API.

https://github.com/opencoca/RIAC-snapCloud/blob/master/migrations.patch

**Comment by cycomachead** [comment]
I think we've now cleaned this up, finally.
