### ISSUE TITLE
Installation on debian-12 fails

### ISSUE THREAD

**Issue by craff** [snap-cloud/snapCloud#347]
argparse is needed and fails to install:

```
$ sudo luarocks-5.1 install --only-deps snapcloud-dev-0.rockspec 
Using dependencies pinned in lockfile: ./luarocks.lock
snapcloud dev-0 is pinned to ansicolors 1.0.2-3 (1.0.2-3 installed)
snapcloud dev-0 is pinned to argparse scm-2 (not installed)

Error: Could not satisfy dependency argparse scm-2: No results matching query were found for Lua 5.1.
```

**Comment by craff** [comment]
Michael Ball ***@***.***> writes:

> Yeah, I don't know what happened recently(ish) with argparse. It's safe to install without the lock file, or to manually install argparse then fix the lock file
> version.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.

What do you mean by manual install ? Using luarocks-5.1 gives the same
error.


--
Christophe Raffalli
tél: +689 87 23 11 48
web: http://raffalli.eu
my mails should pass DKIM/SPF tests/mes messages doivent passer les tests DKIM/SPF

**Comment by cycomachead** [comment]
I think you can just `luarocks install argparse`

I used the macOS wrapper (that just defaults to 5.1 and finds the right cflags), but the same thing should work:
```
👉 ./bin/luarocks-macos install argparse
Installing https://luarocks.org/argparse-0.7.1-1.src.rock

argparse 0.7.1-1 depends on lua >= 5.1, < 5.5 (5.1-1 provided by VM)
argparse 0.7.1-1 is now installed in /Volumes/Michael/Users/michael/.luarocks (license: MIT)

Checking stability of dependencies in the absence of
argparse scm-2...

Removing argparse scm-2...
Removal successful.
```

At some point I was going to figure out exactly what happened with argparse or just regenerate the rockspec.

**Comment by wwj718** [comment]
`INSTALL.md` does not work properly on MacOS. There seems to be more than one error. Is it possible to update it?
