### ISSUE TITLE
Setup log rotation (+ archiving?)

### ISSUE THREAD

**Issue by cycomachead** [snap-cloud/snapCloud#65]
It seems like it'd be nice to keep the log files smaller and easier to manage. Ubuntu's log rotate command is pretty is to configure (we can just add a file to the repo and create the cron job.)

https://www.digitalocean.com/community/tutorials/how-to-manage-logfiles-with-logrotate-on-ubuntu-16-04
https://www.digitalocean.com/community/tutorials/how-to-use-logrotate-and-s3cmd-to-archive-logs-to-object-storage-on-ubuntu-16-04

**Comment by cycomachead** [comment]
I didn't get this right so I need to redo it. :/ 

Our current access.log is 38 million lines! 😱

**Comment by bromagosa** [comment]
Yep, I noticed haha. I still didn't mind much because GNU text utilities are extremely fast, but when logs get (even) longer things will get a bit slow.

**Comment by cycomachead** [comment]
This is finally working... There's now a log file per-day, with the name of the date at the end of the filename.
